openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: action-controller
    description: Action Controller
paths:
  '/atp-itf-lite/api/v1/actions':
    get:
      tags:
        - action-controller
      summary: getActions
      operationId: getActions
      parameters:
        - name: projectId
          in: query
          description: Project identifier
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'models-v1.yaml#/definitions/Action'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found