openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: cookie-controller
    description: Cookie Controller
paths:
  '/atp-itf-lite/api/v1/project/{projectId}/cookies/session/{sessionId}':
    get:
      tags:
        - cookie-controller
      summary: get cookies by session Id
      operationId: getCookiesBySessionId
      parameters:
        - name: projectId
          in: path
          description: Project identifier
          required: true
          schema:
            type: string
            format: uuid
        - name: sessionId
          in: path
          description: session identifier
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'models-v1.yaml#/definitions/CookiesDto'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - cookie-controller
      summary: save cookies
      operationId: saveCookies
      parameters:
        - name: projectId
          in: path
          description: Project identifier
          required: true
          schema:
            type: string
            format: uuid
        - name: sessionId
          in: path
          description: session identifier
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: 'models-v1.yaml#/definitions/CookiesDto'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'models-v1.yaml#/definitions/CookiesDto'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found