openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: itf-lite-history-changes-controller
    description: ITF-LITE history changes controller
paths:
  /atp-itf-lite/api/v1/history/{projectId}/{itemType}/{id}:
    get:
      tags:
        - itf-lite-history-changes-controller
      summary: finds all changes history for defined object
      operationId: getAllHistory
      parameters:
        - name: projectId
          in: path
          schema:
            type: string
            format: uuid
            description: project id for current entity
          required: true
        - name: itemType
          in: path
          schema:
            type: string
            description: values from models-v1.yaml#/components/schemas/HistoryItemType must be used
          required: true
        - name: id
          in: path
          schema:
            type: string
            format: uuid
          required: true
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: 'models-v1.yaml#/definitions/HistoryItemResponse'
        '400':
          description: History for Entity type = '" + itemType + "' is not supported
        '404':
          description: Entity Id not found

  /atp-itf-lite/api/v1/history/restore/{projectId}/{itemType}/{id}/revision/{revisionId}:
    post:
      tags:
        - itf-lite-history-changes-controller
      summary: Restore the state of the provided entity to defined revision
      operationId: restoreToRevision
      parameters:
        - name: projectId
          in: path
          schema:
            type: string
            format: uuid
            description: project id for current entity
          required: true
        - name: itemType
          in: path
          schema:
            type: string
            description: values from models-v1.yaml#/definitions/HistoryItemType must be used
          required: true
        - name: id
          in: path
          schema:
            type: string
            format: uuid
            description: uuid of restored entity
          required: true
          example: '83b22327-2f68-4f8b-96ab-1d3670248b9f'
        - name: revisionId
          in: path
          schema:
            type: integer
            description: target revision number for restored entity
          required: true
          example: 3
      responses:
        '200':
          description: 'OK'
        '403':
          description: 'Forbidden'
        '404':
          description: 'Entity Id not found'
        '500':
          description: 'Revision was not restored'

  /atp-itf-lite/api/v1/entityversioning/{projectId}/{itemType}/{uuid}:
    get:
      tags:
        - itf-lite-history-changes-controller
      summary: getEntitiesByVersion
      operationId: getEntitiesByVersion
      parameters:
        - name: projectId
          in: path
          description: projectId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
        - name: itemType
          in: path
          description: itemType
          required: true
          style: simple
          schema:
            type: string
        - name: uuid
          in: path
          description: uuid
          required: true
          style: simple
          schema:
            type: string
            format: uuid
        - name: versions
          in: query
          description: versions
          required: true
          style: form
          explode: true
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: 'models-v1.yaml#/definitions/CompareEntityResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

components:
  schemas:
    HttpRequestHistory:
      allOf:
        - $ref: 'models-v1.yaml#/definitions/Request'
      type: object
      properties:
        folderName:
          type: string
        httpMethod:
          type: string
        url:
          type: string
        requestParams:
          type: array
          items:
            $ref: 'models-v1.yaml#/definitions/RequestParam'
        requestHeaders:
          type: array
          items:
            $ref: 'models-v1.yaml#/definitions/RequestHeader'
        body:
          $ref: 'models-v1.yaml#/definitions/RequestBody'
      title: HttpRequest
    DiameterRequestHistory:
      allOf:
        - $ref: 'models-v1.yaml#/definitions/Request'
      type: object
      properties:
        folderName:
          type: string
        host:
          type: string
        port:
          type: string
        capabilitiesExchangeRequest:
          type: string
        watchdogDefaultTemplate:
          type: string
        connectionLayer:
          type: string
        responseType:
          type: string
        messageFormat:
          type: string
        dictionaryType:
          type: string
        responseTimeout:
          type: integer
        body:
          $ref: 'models-v1.yaml#/definitions/RequestBody'
        dictionary:
          type: string
      title: DiameterRequest
