openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: auth-action-controller
    description: Auth action controller
paths:
  '/atp-itf-lite/api/v1/authAction/saveParamsForGetAccessCode':
    post:
      tags:
        - auth-action-controller
      summary: save parameters for Get Access Code
      operationId: saveParamsForGetAccessCode
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'models-v1.yaml#/definitions/GetAccessCodeParameters'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/atp-itf-lite/api/v1/authAction/saveCode/{sseId}':
    get:
      tags:
        - auth-action-controller
      summary: save authorizationCode for Get Access Code
      operationId: saveCode
      parameters:
        - name: sseId
          in: path
          description: SSE identifier
          required: true
          schema:
            type: string
            format: uuid
        - name: code
          in: query
          description: Authorization Code
          required: true
          schema:
            type: string
        - name: state
          in: query
          description: Authorization state
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
        '403':
          description: Forbidden
        '404':
          description: Not Found
