openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: request-controller
    description: Request Controller
paths:
  '/atp-itf-lite/api/v1/requests':
    get:
      tags:
        - request-controller
      summary: getAllRequests
      operationId: getAllRequests
      parameters:
        - name: projectId
          in: query
          description: Project identifier
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - $ref: 'models-v1.yaml#/definitions/HttpRequest'
                    - $ref: 'models-v1.yaml#/definitions/DiameterRequest'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - request-controller
      summary: createRequest
      operationId: createRequest
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'models-v1.yaml#/definitions/RequestEntityCreateRequest'
      responses:
        '201':
          description: Created
          content:
            'application/json':
              schema:
                oneOf:
                  - $ref: 'models-v1.yaml#/definitions/HttpRequest'
                  - $ref: 'models-v1.yaml#/definitions/DiameterRequest'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - request-controller
      summary: deleteRequests
      operationId: deleteRequests
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'models-v1.yaml#/definitions/RequestEntitiesDeleteRequest'
      responses:
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

  '/atp-itf-lite/api/v1/requests/{id}':
    get:
      tags:
        - request-controller
      summary: getRequest
      operationId: getRequest
      parameters:
        - name: projectId
          in: query
          description: projectId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
        - name: id
          in: path
          description: request id
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                oneOf:
                  - $ref: 'models-v1.yaml#/definitions/HttpRequest'
                  - $ref: 'models-v1.yaml#/definitions/DiameterRequest'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    put:
      tags:
        - request-controller
      summary: saveRequest
      operationId: saveRequest
      parameters:
        - name: projectId
          in: query
          description: Project identifier
          required: false
          schema:
            type: string
            format: uuid
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: object
                requestEntity:
                  type: object
                  oneOf:
                    - $ref: 'models-v1.yaml#/definitions/HttpRequestEntitySaveRequest'
                    - $ref: 'models-v1.yaml#/definitions/DiameterRequestEntitySaveRequest'
                files:
                  type: array
                  format: object
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                oneOf:
                  - $ref: 'models-v1.yaml#/definitions/HttpRequest'
                  - $ref: 'models-v1.yaml#/definitions/DiameterRequest'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    patch:
      tags:
        - request-controller
      summary: editRequest
      operationId: editRequest
      parameters:
        - name: projectId
          in: query
          description: Project identifier
          required: false
          schema:
            type: string
            format: uuid
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'models-v1.yaml#/definitions/RequestEntityEditRequest'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                oneOf:
                  - $ref: 'models-v1.yaml#/definitions/HttpRequest'
                  - $ref: 'models-v1.yaml#/definitions/DiameterRequest'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - request-controller
      summary: deleteRequest
      operationId: deleteRequest
      parameters:
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

  '/atp-itf-lite/api/v1/requests/{id}/copy':
    post:
      tags:
        - request-controller
      summary: copyRequest
      operationId: copyRequest
      parameters:
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'models-v1.yaml#/definitions/RequestEntityCopyRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - $ref: 'models-v1.yaml#/definitions/HttpRequest'
                    - $ref: 'models-v1.yaml#/definitions/DiameterRequest'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

  '/atp-itf-lite/api/v1/requests/{id}/move':
    post:
      tags:
        - request-controller
      summary: moveRequest
      operationId: moveRequest
      parameters:
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'models-v1.yaml#/definitions/RequestEntityMoveRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - $ref: 'models-v1.yaml#/definitions/HttpRequest'
                    - $ref: 'models-v1.yaml#/definitions/DiameterRequest'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

  '/atp-itf-lite/api/v1/requests/copy':
    post:
      tags:
        - request-controller
      summary: copyRequests
      operationId: copyRequests
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'models-v1.yaml#/definitions/RequestEntitiesCopyRequest'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

  '/atp-itf-lite/api/v1/requests/move':
    post:
      tags:
        - request-controller
      summary: moveRequests
      operationId: moveRequests
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'models-v1.yaml#/definitions/RequestEntitiesMoveRequest'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

  '/atp-itf-lite/api/v1/requests/{id}/export':
    get:
      deprecated: true
      tags:
        - request-controller
      summary: exportRequest
      operationId: exportRequest
      parameters:
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: string
            format: uuid
        - name: environmentId
          in: query
          description: environmentId
          required: false
          style: simple
          schema:
            type: string
            format: uuid
        - name: context
          in: query
          description: ITF context
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'models-v1.yaml#/definitions/RequestExportResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - request-controller
      summary: exportRequest
      operationId: exportRequest
      parameters:
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: string
            format: uuid
        - name: environmentId
          in: query
          description: environmentId
          required: false
          style: simple
          schema:
            type: string
            format: uuid
        - name: context
          in: query
          description: ITF context
          required: false
          schema:
            type: string
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: 'models-v1.yaml#/definitions/ContextVariable'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'models-v1.yaml#/definitions/RequestExportResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

  '/atp-itf-lite/api/v1/requests/import':
    post:
      tags:
        - request-controller
      summary: importRequest
      operationId: importRequest
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'models-v1.yaml#/definitions/CurlStringImportRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'models-v1.yaml#/definitions/HttpRequest'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

  '/atp-itf-lite/api/v1/requests/context':
    get:
      tags:
        - request-controller
      summary: itf context
      operationId: context
      parameters:
        - name: projectId
          in: query
          description: projectId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
        - name: contextId
          in: query
          description: contextId
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

  '/atp-itf-lite/api/v1/requests/{id}/dictionary':
    get:
      tags:
        - request-controller
      summary: getDiameterRequestDictionary
      operationId: getDiameterRequestDictionary
      parameters:
        - name: id
          in: path
          description: request id
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/atp-itf-lite/api/v1/requests/{id}/settings':
    get:
      tags:
        - request-controller
      summary: get request settings
      operationId: getRequestSettings
      parameters:
        - name: id
          in: path
          description: request id
          schema:
            type: string
            format: uuid
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: 'models-v1.yaml#/definitions/Settings'
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
