openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: request-headers-controller
    description: Request headers Controller
paths:

    '/atp-itf-lite/api/v1/request-headers/{id}/disable':
      post:
        tags:
          - request-headers-controller
        summary: disableRequestHeader
        operationId: disableRequestHeader
        parameters:
          - name: id
            in: path
            description: Header id
            schema:
              type: string
              format: uuid
          - name: projectId
            in: query
            description: Project identifier
            schema:
              type: string
              format: uuid
          - name: requestId
            in: query
            description: Request identifier
            schema:
              type: string
              format: uuid
        responses:
          '200':
            description: OK
          '401':
            description: Unauthorized
          '403':
            description: Forbidden
          '404':
            description: Not Found
    '/atp-itf-lite/api/v1/request-headers/{id}/enable':
      post:
        tags:
          - request-headers-controller
        summary: enableRequestHeader
        operationId: enableRequestHeader
        parameters:
          - name: id
            in: path
            description: Header id
            schema:
              type: string
              format: uuid
          - name: projectId
            in: query
            description: Project identifier
            schema:
              type: string
              format: uuid
          - name: requestId
            in: query
            description: Request identifier
            schema:
              type: string
              format: uuid
        responses:
          '200':
            description: OK
          '401':
            description: Unauthorized
          '403':
            description: Forbidden
          '404':
            description: Not Found