openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: sse-controller
    description: SSE Controller
paths:
  '/atp-itf-lite/api/v1/sse/requests/connect':
    get:
      tags:
        - sse-controller
      summary: sseConnect
      operationId: sseConnect
      parameters:
        - name: projectId
          in: query
          description: projectId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
        - name: sseId
          in: query
          description: sseId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

  '/atp-itf-lite/api/v1/sse/requests/{id}/execute':
    post:
      tags:
        - sse-controller
      summary: executeRequest
      operationId: executeRequest
      parameters:
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: string
            format: uuid
        - name: sseId
          in: query
          description: sseId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
        - name: contextId
          in: query
          description: contextId
          required: false
          style: simple
          schema:
            type: string
            format: uuid
        - name: environmentId
          in: query
          description: environmentId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: object
                requestEntity:
                  type: object
                  oneOf:
                    - $ref: 'models-v1.yaml#/definitions/HttpRequestEntitySaveRequest'
                    - $ref: 'models-v1.yaml#/definitions/DiameterRequestEntitySaveRequest'
                files:
                  type: array
                  format: object
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

  '/atp-itf-lite/api/v1/sse/requests/mia/export':
    post:
      tags:
        - sse-controller
      summary: miaExportRequests
      operationId: miaExportRequests
      parameters:
        - name: sseId
          in: query
          description: sseId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
        - name: contextId
          in: query
          description: contextId
          required: false
          style: simple
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              schema:
                $ref: 'models-v1.yaml#/definitions/RequestMiaExportRequest'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found


  '/atp-itf-lite/api/v1/sse/requests/itf/export':
    post:
      tags:
        - sse-controller
      summary: itfExportRequests
      operationId: itfExportRequests
      parameters:
        - name: sseId
          in: query
          description: sseId
          required: true
          style: simple
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              schema:
                $ref: 'models-v1.yaml#/definitions/RequestItfExportRequest'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
