---
kind: Service
apiVersion: v1
metadata:
  name: '{{ .Values.SERVICE_NAME }}'
spec:
  ports:
  - port: 8080
    name: web
    protocol: TCP
  selector:
    name: '{{ .Values.SERVICE_NAME }}'
  type: NodePort
