image:
  registry: docker.io
  repository: bitnami/kafka

kraft:
  enabled: false

broker:
  replicaCount: 3

controller:
  replicaCount: 0

zookeeper:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/zookeeper
  auth:
    enabled: false

auth:
  enabled: false
  clientProtocol: plaintext
  interBrokerProtocol: plaintext

persistence:
  enabled: false

externalAccess:
  enabled: false
