# Which docker image should be used to deploy
DOCKER_TAG: "ghcr.io/netcracker/qubership-testing-platform-itf-lite-backend:test_pipeline-20250923062118"
# This option turns on or off logging in graylog
GRAYLOG_ON: "false"
KAFKA_REPORTING_SERVERS: ""
# Keycloak enabled
KEYCLOAK_ENABLED: "false"
# IP of db
PG_DB_ADDR: "my-postgres-postgresql"
# Spring profile for security
SPRING_PROFILES: "disable-security"
keepHookLogs: true
HELPER_IMAGE: "ghcr.io/netcracker/qubership-testing-platform-helm-hook-helper:main-20250714085543"
CONTENT_SECURITY_POLICY: "*"
pg_pass: "postgrestest"
pg_user: "postgres"
HAZELCAST_ENABLE: false
EI_CLEAN_JOB_ENABLED: "false"
JAVERS_ENABLED: "false"
EI_GRIDFS_ENABLED: "false"
SERVICE_ENTITIES_MIGRATION_ENABLED: "false"
GRIDFS_DB_ADDR: "my-mongodb"
KAFKA_SERVERS: "my-kafka-controller-0.my-kafka-controller-headless.lite.svc.cluster.local:9092,my-kafka-controller-1.my-kafka-controller-headless.lite.svc.cluster.local:9092,my-kafka-controller-2.my-kafka-controller-headless.lite.svc.cluster.local:9092"
