ALTER TABLE IF EXISTS JV_GLOBAL_ID
DROP CONSTRAINT IF EXISTS JV_GLOBAL_ID_OWNER_ID_FK,
	ADD CONSTRAINT JV_GLOBAL_ID_OWNER_ID_FK
		FOREIGN KEY (OWNER_ID_FK)
			REFERENCES JV_GLOBAL_ID(GLOBAL_ID_PK) on delete cascade;