PAAS_PLATFORM: "KUBERNETES"
ATP_NET: ""
# Encyption option. One of - dev (default, encrypt inside app); - secrets (encrypt keys in Openshift secrets); - vault (encrypt keys in Openshift secrets)
ENCRYPT: "secrets"
ADAPTER_TYPE: "kafka"
SERVICE_NAME: "atp-itf-lite-backend"
SERVICE_POD_NAME: ""
DOCKER_TAG: "artifactory-service-address/path-to-image"
ZIPKIN_ENABLE: "false"
ZIPKIN_PROBABILITY: "1.0"
ZIPKIN_URL: "http://zipkin.zipkin.svc:9411"
ATP_INTERNAL_GATEWAY_ENABLED: "true"
FEIGN_ATP_INTERNAL_GATEWAY_NAME: "atp-internal-gateway"
FEIGN_ATP_RAM_URL: ""
FEIGN_ATP_RAM_NAME: "ATP-RAM"
FEIGN_ATP_RAM_ROUTE: "api/atp-ram/v1"
FEIGN_ATP_CATALOGUE_URL: ""
FEIGN_ATP_CATALOGUE_NAME: "ATP-CATALOGUE"
FEIGN_ATP_CATALOGUE_ROUTE: "api/atp-catalogue/v1"
FEIGN_ATP_ITF_LITE_SCRIPT_ENGINE_URL: "http://atp-itf-lite-script-engine:8080"
FEIGN_ATP_ITF_LITE_SCRIPT_ENGINE_NAME: "ATP-IFT-LITE-SCRIPT-ENGINE"
FEIGN_ATP_ITF_LITE_SCRIPT_ENGINE_ROUTE: ""
PROJECT_INFO_ENDPOINT: "/api/v1/users/projects"
FEIGN_ATP_ITF_ENABLED: "true"
FEIGN_ATP_ITF_URL: ""
FEIGN_ATP_ITF_NAME: "ATP-ITF-EXECUTOR"
FEIGN_ATP_ITF_ROUTE: "api/atp-itf-executor/v1"
FEIGN_ATP_USERS_URL: ""
FEIGN_ATP_USERS_NAME: "ATP-USERS-BACKEND"
FEIGN_ATP_USERS_ROUTE: "api/atp-users-backend/v1"
FEIGN_ATP_ENVIRONMENTS_URL: ""
FEIGN_ATP_ENVIRONMENTS_NAME: "ATP-ENVIRONMENTS"
FEIGN_ATP_ENVIRONMENTS_ROUTE: "api/atp-environments/v1"
FEIGN_ATP_MACROS_URL: ""
FEIGN_ATP_MACROS_NAME: "ATP-MACROS"
FEIGN_ATP_MACROS_ROUTE: "api/atp-macros/v1"
ATP_ITF_LITE_CONNECTION_TIMEOUT: "30000"
ATP_ITF_LITE_REQUEST_TIMEOUT: "30000"
ATP_ITF_LITE_SOCKET_TIMEOUT: "480000"
ATP_ITF_LITE_SSE_TIMEOUT: "60000"
ATP_ITF_LITE_PING_SSE_TIMEOUT: "30000"
ATP_ITF_LITE_HTTP_REQUEST_SIZE_MB: "100"
ATP_ITF_LITE_HTTP_RESPONSE_SIZE_MB: "100"
ATP_ITF_LITE_MAX_TOTAL_CONNECTIONS: "100"
ATP_ITF_LITE_DEFAULT_KEEP_ALIVE_TIME_MILLIS: "20000"
ATP_ITF_LITE_CLOSE_IDLE_CONNECTION_WAIT_TIME: "30"
ATP_CATALOGUE_URL: "https://atp-catalogue-service-address"
GRAYLOG_HOST: "tcp:graylog-service-address"
GRAYLOG_PORT: "12201"
GRAYLOG_ON: "true"
CPU_REQUEST: "0.05"
CPU_LIMIT: "0.5"
MEMORY_REQUEST: "300Mi"
MEMORY_LIMIT: "1.5Gi"
SPRING_PROFILES: "default"
KEYCLOAK_AUTH_URL: "https://atp-keycloak-service-address/auth"
KEYCLOAK_ENABLED: "true"
KEYCLOAK_REALM: "atp2"
KEYCLOAK_CLIENT_NAME: "atp-itf-lite"
KEYCLOAK_SECRET: "290238dd-5e4b-40ff-9b18-8b5ebcd628d5"
MAX_RAM: "1024m"
EUREKA_CLIENT_ENABLED: "false"
SERVICE_REGISTRY_URL: "http://atp-registry-service:8761/eureka"
PG_DB_ADDR: "pg-common.postgrescluster.svc"
PG_DB_PORT: "5432"
# SSL enabling for ingresses
TLS_ENABLED: true
# Security Context properties
# enabled is a flag to enable Security Context
SECURITY_CONTEXT_ENABLED: false
# runAsUser is the user ID used to run the container
SECURITY_RUN_AS_USER: 1000
# fsGroup is the group ID associated with the container
SECURITY_FS_GROUP: 1000
# atp-itf-lite gridfs host
GRIDFS_DB_ADDR: "mongos.mongocluster.svc"
# atp-itf-lite gridfs port
GRIDFS_DB_PORT: "27017"
MAX_CONNECTION_IDLE_TIME: "0"
MIN_CONNECTIONS_PER_HOST: "40"
CONNECTIONS_PER_HOST: "100"
GRID_DICTIONARY_REMOVE_DAYS: "30"
GRID_CHUNK_SIZE: "1024"
HISTORY_RETENTION_IN_DAYS: "14"
HISTORY_RETENTION_CRON_EXPRESSION: "0 0 2 ? * *"
GET_ACCESS_TOKEN_RETENTION_CRON_EXPRESSION: "0 30 2 ? * *"
########## KAFKA CONFIG ##########
KAFKA_SERVERS: "kafka.kafka-cluster.svc:9092"
KAFKA_CATALOG_GROUP: ""
KAFKA_CATALOG_TOPIC: ""
KAFKA_ENVIRONMENT_TOPIC: ""
KAFKA_ITF_LITE_EXPORT_MIA_PARTITIONS: "3"
KAFKA_ITF_LITE_EXPORT_MIA_REPLICAS: ""
KAFKA_ITF_LITE_EXPORT_ITF_PARTITIONS: "3"
KAFKA_ITF_LITE_EXPORT_ITF_REPLICAS: ""
KAFKA_LOGRECORD_TOPIC: ""
KAFKA_LOGRECORD_TOPIC_PARTITIONS: "1"
KAFKA_LOGRECORD_TOPIC_REPLICATION_FACTOR: ""
KAFKA_LOGRECORD_CONTEXT_TOPIC: ""
KAFKA_LOGRECORD_CONTEXT_TOPIC_PARTITIONS: "1"
KAFKA_LOGRECORD_CONTEXT_TOPIC_REPLICATION_FACTOR: ""
KAFKA_SERVICE_ENTITIES_TOPIC: ""
KAFKA_SERVICE_ENTITIES_TOPIC_PARTITIONS: "1"
KAFKA_SERVICE_ENTITIES_TOPIC_REPLICATION_FACTOR: ""
SERVICE_ENTITIES_MIGRATION_ENABLED: "true"
KAFKA_ITF_LITE_EXECUTION_FINISH_PARTITIONS: "1"
KAFKA_ITF_LITE_EXECUTION_FINISH_REPLICAS: ""
KAFKA_ITF_LITE_GET_ACCESS_TOKEN_FINISH_TOPIC: ""
KAFKA_ITF_LITE_GET_ACCESS_TOKEN_FINISH_PARTITIONS: "3"
KAFKA_ITF_LITE_GET_ACCESS_TOKEN_FINISH_REPLICAS: ""
KAFKA_LOGRECORD_SCRIPTS_TOPIC: ""
KAFKA_LOGRECORD_SCRIPTS_TOPIC_PARTITIONS: "3"
KAFKA_LOGRECORD_SCRIPTS_TOPIC_REPLICATION_FACTOR: ""
NODES_COUNT: "1"
######### KAFKA CONFIG ##########
# Audit Logging topic
AUDIT_LOGGING_ENABLE: "false"
AUDIT_LOGGING_TOPIC_NAME: ""
KAFKA_REPORTING_SERVERS: "kafka:9092"
AUDIT_LOGGING_TOPIC_PARTITIONS: "1"
AUDIT_LOGGING_TOPIC_REPLICAS: ""
######### ATP NOTIFICATION ##########
ATP_NOTIFICATION_MODE: "kafka"
KAFKA_NOTIFICATION_TOPIC_REPLICATION_FACTOR: ""
KAFKA_NOTIFICATION_TOPIC_MIN_INSYNC_REPLICATION_FACTOR: ""
KAFKA_NOTIFICATION_TOPIC_PARTITIONS: "1"
## feign client for atp-notification service
FEIGN_ATP_NOTIFICATION_URL: ""
FEIGN_ATP_NOTIFICATION_NAME: "ATP-NOTIFICATION"
FEIGN_ATP_NOTIFICATION_ROUTE: "api/atp-notification/v1"
######### ATP NOTIFICATION ##########
JMX_ENABLE: "true"
JMX_PORT: "3000"
JMX_RMI_PORT: "3001"
######### HAZELCAST ##########
# Name of the deployed hazelcast cluster to connect to
HAZELCAST_CLUSTER_NAME: "atp-hc"
# Whether to cache using hazelcast
HAZELCAST_CLIENT_ENABLED: "false"
# Whether hazelcast server is available
HAZELCAST_SERVER_ENABLED: "false"
# Hazelcast address
HAZELCAST_ADDRESS: "atp-hazelcast:5701"
# Name mongo grid DB
EI_GRIDFS_DB: ""
# Password mongo grid DB
EI_GRIDFS_PASSWORD: ""
# User mongo grid DB
EI_GRIDFS_USER: ""
FEIGN_ATP_EI_NAME: "ATP-EXPORT-IMPORT"
FEIGN_ATP_EI_ROUTE: "api/atp-export-import/v1"
FEIGN_ATP_EI_URL: "" # TO_BE_REPLACED
EI_CLEAN_JOB_ENABLED: "true"
EI_CLEAN_JOB_WORKDIR: "exportimport/node"
EI_CLEAN_SCHEDULED_JOB_PERIOD_MS: "86400000"
EI_CLEAN_JOB_FILE_DELETE_AFTER_MS: "172800000"
# Consul
CONSUL_PREFIX: "devci"
CONSUL_ENABLED: "false"
CONSUL_HEALTH_CHECK_ENABLED: "false"
CONSUL_URL: ""
CONSUL_PORT: 8500
CONSUL_TOKEN: ""
SERVICE_TYPE: "ATP2"
# http logging
ATP_HTTP_LOGGING: "true"
ATP_HTTP_LOGGING_HEADERS: "true"
ATP_HTTP_LOGGING_HEADERS_IGNORE: "Authorization"
ATP_HTTP_LOGGING_URI_IGNORE: "/atp-itf-lite/api/v1/sse/.* /rest/deployment/readiness /rest/deployment/liveness"
# logging level root
LOG_LEVEL: "INFO"
#  kubernetes.io/hostname: worker-kuber
#Example:  "nodeSelector": {"kubernetes.io/hostname": "worker-kuber"}
nodeSelector: {}
ITF_LITE_CLEAN_CACHED_FILES: "3600"
CLEANUP_COLLECTION_RUNS_CRON_EXPRESSION: "0 0 0 * * ?"
CLEANUP_COOKIES_CRON_EXPRESSION: "0 0 * * * *"
CLEANUP_SNAPSHOTS_CRON_EXPRESSION: "0 0 0 * * ?"
CLEANUP_SNAPSHOTS_EXPIRATION_PERIOD_SECONDS: "86400"
COLLECTION_RUNS_REMOVE_DAYS: "1"
HEAPDUMP_ENABLED: false

# Javers
JAVERS_ENABLED: "true"
HISTORY_CLEAN_JOB_EXPRESSION: "0 10 0 * * ?"
HISTORY_CLEAN_JOB_PAGE_SIZE: "100"
HISTORY_CLEAN_JOB_REVISION_MAX_COUNT: "100"
# Swagger
SWAGGER_ENABLED: "false"
#Example: "extraEnvs": [
#    {
#      "name": "DISABLE_INSTALL_DEMO_CONFIG",
#      "value": "true"
#    },
#    {
#      "name": "DISABLE_SECURITY_PLUGIN",
#      "value": "true"
#    }
#  ]
extraEnvs: []
keepHookLogs: false
HELPER_IMAGE: "artifactory-service-address/path-to-image"
ADDITIONAL_JAVA_OPTIONS: "-XX:MaxRAMPercentage=70.0"
